const fs = require('node:fs')

const data = [
  {
    id: 1,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '15/12/22',
    heure_normale: 8,
    heure_de_travail: '10',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 2,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '16/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 3,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '17/12/22',
    heure_normale: 8,
    heure_de_travail: '10',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 4,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '18/12/22',
    heure_normale: 8,
    heure_de_travail: '8.5',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 5,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '19/12/22',
    heure_normale: 8,
    heure_de_travail: '5.3',
    hs_de_nuit: 3,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 6,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '20/12/22',
    heure_normale: 8,
    heure_de_travail: '8.1',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 7,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '21/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 8,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '22/12/22',
    heure_normale: 8,
    heure_de_travail: '8.5',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 9,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '23/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 10,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '24/12/22',
    heure_normale: 8,
    heure_de_travail: '8.2',
    hs_de_nuit: 2,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 11,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '25/12/22',
    heure_normale: 8,
    heure_de_travail: '8.15',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 12,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '26/12/22',
    heure_normale: 8,
    heure_de_travail: '8.02',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 13,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '27/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 14,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '28/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 15,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '29/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 16,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '30/12/22',
    heure_normale: 8,
    heure_de_travail: '8.4',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 17,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '31/12/22',
    heure_normale: 8,
    heure_de_travail: '8.13',
    hs_de_nuit: 5,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 18,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '01/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 19,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '02/01/23',
    heure_normale: 8,
    heure_de_travail: '8.3',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 20,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '03/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 21,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '04/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 22,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '05/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 23,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '06/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 24,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '07/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 25,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '08/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 26,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '09/01/23',
    heure_normale: 8,
    heure_de_travail: '8.1',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 27,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '10/01/23',
    heure_normale: 8,
    heure_de_travail: '8.25',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 28,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '11/01/23',
    heure_normale: 8,
    heure_de_travail: '8.1',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 29,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '12/01/23',
    heure_normale: 8,
    heure_de_travail: '9',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 30,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '13/01/23',
    heure_normale: 8,
    heure_de_travail: '10',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 31,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '14/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 32,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '15/01/23',
    heure_normale: 8,
    heure_de_travail: '10.2',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 33,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '16/01/23',
    heure_normale: 8,
    heure_de_travail: '12',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 34,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '17/01/23',
    heure_normale: 8,
    heure_de_travail: '10',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 35,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '18/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 36,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '19/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 37,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '20/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 38,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '21/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 39,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '22/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 40,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '23/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 41,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '24/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 42,
    employee: {
      id: 1,
      matricule: 345,
    },
    date: '25/01/23',
    heure_normale: 8,
    heure_de_travail: '10',
    hs_de_nuit: null,
    hs_jours_feries: 10,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 43,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '15/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 44,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '16/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 45,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '17/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 46,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '18/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 47,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '19/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 48,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '20/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 49,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '21/12/22',
    heure_normale: 8,
    heure_de_travail: '10',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 50,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '22/12/22',
    heure_normale: 8,
    heure_de_travail: '8.2',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 51,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '23/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 52,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '24/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 53,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '25/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 54,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '26/12/22',
    heure_normale: 8,
    heure_de_travail: '8.2',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 55,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '27/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 56,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '28/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 57,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '29/12/22',
    heure_normale: 8,
    heure_de_travail: '8.3',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 58,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '30/12/22',
    heure_normale: 8,
    heure_de_travail: '8.5',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 59,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '31/12/22',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 60,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '01/01/23',
    heure_normale: 8,
    heure_de_travail: '8.1',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 61,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '02/01/23',
    heure_normale: 8,
    heure_de_travail: '8.6',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 62,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '03/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 63,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '04/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 64,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '05/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 65,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '06/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 66,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '07/01/23',
    heure_normale: 8,
    heure_de_travail: '8.1',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 67,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '08/01/23',
    heure_normale: 8,
    heure_de_travail: '8.3',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 68,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '09/01/23',
    heure_normale: 8,
    heure_de_travail: '8.6',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 69,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '10/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 70,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '11/01/23',
    heure_normale: 8,
    heure_de_travail: '9',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 71,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '12/01/23',
    heure_normale: 8,
    heure_de_travail: '10',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 72,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '13/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 73,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '14/01/23',
    heure_normale: 8,
    heure_de_travail: '8.7',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 74,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '15/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 75,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '16/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 76,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '17/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 77,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '18/01/23',
    heure_normale: 8,
    heure_de_travail: '9',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 78,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '19/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 79,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '20/01/23',
    heure_normale: 8,
    heure_de_travail: '8.4',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 80,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '21/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 81,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '22/01/23',
    heure_normale: 8,
    heure_de_travail: '8.2',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 82,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '23/01/23',
    heure_normale: 8,
    heure_de_travail: '10',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 83,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '24/01/23',
    heure_normale: 8,
    heure_de_travail: '10.1',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 84,
    employee: {
      id: 2,
      matricule: 619,
    },
    date: '25/01/23',
    heure_normale: 8,
    heure_de_travail: '8',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 85,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '15/12/22',
    heure_normale: 8,
    heure_de_travail: '0,1',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 86,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '16/12/22',
    heure_normale: 8,
    heure_de_travail: '3',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 87,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '17/12/22',
    heure_normale: 8,
    heure_de_travail: '4',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 88,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '18/12/22',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 89,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '19/12/22',
    heure_normale: 8,
    heure_de_travail: '2',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 90,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '20/12/22',
    heure_normale: 8,
    heure_de_travail: '2',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 91,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '21/12/22',
    heure_normale: 8,
    heure_de_travail: '1',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 92,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '22/12/22',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 93,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '23/12/22',
    heure_normale: 8,
    heure_de_travail: '0,9',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 94,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '24/12/22',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 95,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '25/12/22',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 96,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '26/12/22',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 97,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '27/12/22',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 98,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '28/12/22',
    heure_normale: 8,
    heure_de_travail: '3',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 99,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '29/12/22',
    heure_normale: 8,
    heure_de_travail: '2',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 100,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '30/12/22',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 101,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '31/12/22',
    heure_normale: 8,
    heure_de_travail: '1',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 102,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '01/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 103,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '02/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 104,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '03/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 105,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '04/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 106,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '05/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 107,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '06/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 108,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '07/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 109,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '08/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 110,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '09/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 111,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '10/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 112,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '11/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 113,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '12/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 114,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '13/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 115,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '14/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 116,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '15/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 117,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '16/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 118,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '17/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 119,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '18/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 120,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '19/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 121,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '20/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 122,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '21/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 123,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '22/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 124,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '23/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 125,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '24/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
  {
    id: 126,
    employee: {
      id: 4,
      matricule: 869,
    },
    date: '25/01/23',
    heure_normale: 8,
    heure_de_travail: '',
    hs_de_nuit: null,
    hs_jours_feries: null,
    hs_de_nuit_30: '',
    hs_de_nuit_50: '',
  },
]

const a = data.map((item) => ({
  ...item,
  employee: {
    id: item.employee.id,
    matricule: item.employee.matricule.toString(),
  },
  heure_de_travail: parseFloat(item.heure_de_travail),
}))

// Write the modified data to a file
fs.writeFile('api/db/jsonConverted.json', JSON.stringify(a), (err) => {
  if (err) {
    console.error(err)
  } else {
    console.log('File updated successfully.')
  }
})
