const fs = require('node:fs')
const path = require('path')

const data = [
  {
    id: 1,
    employee: { id: 1, matricule: 345 },
    date: '15/12/2022',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 2,
    employee: { id: 1, matricule: 345 },
    date: '16/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 3,
    employee: { id: 1, matricule: 345 },
    date: '17/12/2022',
    heure_normale: 8,
    heure_de_travail: '10',
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 4,
    employee: { id: 1, matricule: 345 },
    date: '18/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.5,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 5,
    employee: { id: 1, matricule: 345 },
    date: '19/12/2022',
    heure_normale: 8,
    heure_de_travail: 5.3,
    hs_de_nuit: [3, ''],
    hs_jours_feries: null,
  },
  {
    id: 6,
    employee: { id: 1, matricule: 345 },
    date: '20/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.1,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 7,
    employee: { id: 1, matricule: 345 },
    date: '21/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 8,
    employee: { id: 1, matricule: 345 },
    date: '22/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.5,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 9,
    employee: { id: 1, matricule: 345 },
    date: '23/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 10,
    employee: { id: 1, matricule: 345 },
    date: '24/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.2,
    hs_de_nuit: [2, ''],
    hs_jours_feries: null,
  },
  {
    id: 11,
    employee: { id: 1, matricule: 345 },
    date: '25/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.15,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 12,
    employee: { id: 1, matricule: 345 },
    date: '26/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.02,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 13,
    employee: { id: 1, matricule: 345 },
    date: '27/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 14,
    employee: { id: 1, matricule: 345 },
    date: '28/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 15,
    employee: { id: 1, matricule: 345 },
    date: '29/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 16,
    employee: { id: 1, matricule: 345 },
    date: '30/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.4,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 17,
    employee: { id: 1, matricule: 345 },
    date: '31/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.13,
    hs_de_nuit: [5, ''],
    hs_jours_feries: null,
  },
  {
    id: 18,
    employee: { id: 1, matricule: 345 },
    date: '01/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 19,
    employee: { id: 1, matricule: 345 },
    date: '02/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.3,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 20,
    employee: { id: 1, matricule: 345 },
    date: '03/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 21,
    employee: { id: 1, matricule: 345 },
    date: '04/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 22,
    employee: { id: 1, matricule: 345 },
    date: '05/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 23,
    employee: { id: 1, matricule: 345 },
    date: '06/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 24,
    employee: { id: 1, matricule: 345 },
    date: '07/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 25,
    employee: { id: 1, matricule: 345 },
    date: '08/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 26,
    employee: { id: 1, matricule: 345 },
    date: '09/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.1,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 27,
    employee: { id: 1, matricule: 345 },
    date: '10/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.25,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 28,
    employee: { id: 1, matricule: 345 },
    date: '11/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.1,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 29,
    employee: { id: 1, matricule: 345 },
    date: '12/01/2023',
    heure_normale: 8,
    heure_de_travail: 9,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 30,
    employee: { id: 1, matricule: 345 },
    date: '13/01/2023',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 31,
    employee: { id: 1, matricule: 345 },
    date: '14/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 32,
    employee: { id: 1, matricule: 345 },
    date: '15/01/2023',
    heure_normale: 8,
    heure_de_travail: 10.2,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 33,
    employee: { id: 1, matricule: 345 },
    date: '16/01/2023',
    heure_normale: 8,
    heure_de_travail: 12,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 34,
    employee: { id: 1, matricule: 345 },
    date: '17/01/2023',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 35,
    employee: { id: 1, matricule: 345 },
    date: '18/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 36,
    employee: { id: 1, matricule: 345 },
    date: '19/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 37,
    employee: { id: 1, matricule: 345 },
    date: '20/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 38,
    employee: { id: 1, matricule: 345 },
    date: '21/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 39,
    employee: { id: 1, matricule: 345 },
    date: '22/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 40,
    employee: { id: 1, matricule: 345 },
    date: '23/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 41,
    employee: { id: 1, matricule: 345 },
    date: '24/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 42,
    employee: { id: 1, matricule: 345 },
    date: '25/01/2023',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: 10,
  },
  {
    id: 43,
    employee: { id: 2, matricule: 619 },
    date: '15/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 44,
    employee: { id: 2, matricule: 619 },
    date: '16/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 45,
    employee: { id: 2, matricule: 619 },
    date: '17/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 46,
    employee: { id: 2, matricule: 619 },
    date: '18/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 47,
    employee: { id: 2, matricule: 619 },
    date: '19/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 48,
    employee: { id: 2, matricule: 619 },
    date: '20/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 49,
    employee: { id: 2, matricule: 619 },
    date: '21/12/2022',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 50,
    employee: { id: 2, matricule: 619 },
    date: '22/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.2,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 51,
    employee: { id: 2, matricule: 619 },
    date: '23/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 52,
    employee: { id: 2, matricule: 619 },
    date: '24/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 53,
    employee: { id: 2, matricule: 619 },
    date: '25/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 54,
    employee: { id: 2, matricule: 619 },
    date: '26/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.2,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 55,
    employee: { id: 2, matricule: 619 },
    date: '27/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 56,
    employee: { id: 2, matricule: 619 },
    date: '28/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 57,
    employee: { id: 2, matricule: 619 },
    date: '29/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.3,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 58,
    employee: { id: 2, matricule: 619 },
    date: '30/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.5,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 59,
    employee: { id: 2, matricule: 619 },
    date: '31/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 60,
    employee: { id: 2, matricule: 619 },
    date: '01/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.1,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 61,
    employee: { id: 2, matricule: 619 },
    date: '02/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.6,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 62,
    employee: { id: 2, matricule: 619 },
    date: '03/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 63,
    employee: { id: 2, matricule: 619 },
    date: '04/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 64,
    employee: { id: 2, matricule: 619 },
    date: '05/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 65,
    employee: { id: 2, matricule: 619 },
    date: '06/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 66,
    employee: { id: 2, matricule: 619 },
    date: '07/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.1,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 67,
    employee: { id: 2, matricule: 619 },
    date: '08/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.3,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 68,
    employee: { id: 2, matricule: 619 },
    date: '09/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.6,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 69,
    employee: { id: 2, matricule: 619 },
    date: '10/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 70,
    employee: { id: 2, matricule: 619 },
    date: '11/01/2023',
    heure_normale: 8,
    heure_de_travail: 9,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 71,
    employee: { id: 2, matricule: 619 },
    date: '12/01/2023',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 72,
    employee: { id: 2, matricule: 619 },
    date: '13/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 73,
    employee: { id: 2, matricule: 619 },
    date: '14/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.7,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 74,
    employee: { id: 2, matricule: 619 },
    date: '15/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 75,
    employee: { id: 2, matricule: 619 },
    date: '16/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 76,
    employee: { id: 2, matricule: 619 },
    date: '17/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 77,
    employee: { id: 2, matricule: 619 },
    date: '18/01/2023',
    heure_normale: 8,
    heure_de_travail: 9,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 78,
    employee: { id: 2, matricule: 619 },
    date: '19/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 79,
    employee: { id: 2, matricule: 619 },
    date: '20/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.4,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 80,
    employee: { id: 2, matricule: 619 },
    date: '21/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 81,
    employee: { id: 2, matricule: 619 },
    date: '22/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.2,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 82,
    employee: { id: 2, matricule: 619 },
    date: '23/01/2023',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 83,
    employee: { id: 2, matricule: 619 },
    date: '24/01/2023',
    heure_normale: 8,
    heure_de_travail: 10.1,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 84,
    employee: { id: 2, matricule: 619 },
    date: '25/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 85,
    employee: { id: 4, matricule: 869 },
    date: '15/12/2022',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 86,
    employee: { id: 4, matricule: 869 },
    date: '16/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 87,
    employee: { id: 4, matricule: 869 },
    date: '17/12/2022',
    heure_normale: 8,
    heure_de_travail: '10',
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 88,
    employee: { id: 4, matricule: 869 },
    date: '18/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.5,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 89,
    employee: { id: 4, matricule: 869 },
    date: '19/12/2022',
    heure_normale: 8,
    heure_de_travail: 5.3,
    hs_de_nuit: [3, ''],
    hs_jours_feries: null,
  },
  {
    id: 90,
    employee: { id: 4, matricule: 869 },
    date: '20/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.1,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 91,
    employee: { id: 4, matricule: 869 },
    date: '21/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 92,
    employee: { id: 4, matricule: 869 },
    date: '22/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.5,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 93,
    employee: { id: 4, matricule: 869 },
    date: '23/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 94,
    employee: { id: 4, matricule: 869 },
    date: '24/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.2,
    hs_de_nuit: [2, ''],
    hs_jours_feries: null,
  },
  {
    id: 95,
    employee: { id: 4, matricule: 869 },
    date: '25/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.15,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 96,
    employee: { id: 4, matricule: 869 },
    date: '26/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.02,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 97,
    employee: { id: 4, matricule: 869 },
    date: '27/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 98,
    employee: { id: 4, matricule: 869 },
    date: '28/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 99,
    employee: { id: 4, matricule: 869 },
    date: '29/12/2022',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 100,
    employee: { id: 4, matricule: 869 },
    date: '30/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.4,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 101,
    employee: { id: 4, matricule: 869 },
    date: '31/12/2022',
    heure_normale: 8,
    heure_de_travail: 8.13,
    hs_de_nuit: [5, ''],
    hs_jours_feries: null,
  },
  {
    id: 102,
    employee: { id: 4, matricule: 869 },
    date: '01/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 103,
    employee: { id: 4, matricule: 869 },
    date: '02/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.3,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 104,
    employee: { id: 4, matricule: 869 },
    date: '03/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 105,
    employee: { id: 4, matricule: 869 },
    date: '04/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 106,
    employee: { id: 4, matricule: 869 },
    date: '05/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 107,
    employee: { id: 4, matricule: 869 },
    date: '06/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 108,
    employee: { id: 4, matricule: 869 },
    date: '07/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 109,
    employee: { id: 4, matricule: 869 },
    date: '08/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 110,
    employee: { id: 4, matricule: 869 },
    date: '09/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.1,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 111,
    employee: { id: 4, matricule: 869 },
    date: '10/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.25,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 112,
    employee: { id: 4, matricule: 869 },
    date: '11/01/2023',
    heure_normale: 8,
    heure_de_travail: 8.1,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 113,
    employee: { id: 4, matricule: 869 },
    date: '12/01/2023',
    heure_normale: 8,
    heure_de_travail: 9,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 114,
    employee: { id: 4, matricule: 869 },
    date: '13/01/2023',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 115,
    employee: { id: 4, matricule: 869 },
    date: '14/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 116,
    employee: { id: 4, matricule: 869 },
    date: '15/01/2023',
    heure_normale: 8,
    heure_de_travail: 10.2,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 117,
    employee: { id: 4, matricule: 869 },
    date: '16/01/2023',
    heure_normale: 8,
    heure_de_travail: 12,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 118,
    employee: { id: 4, matricule: 869 },
    date: '17/01/2023',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 119,
    employee: { id: 4, matricule: 869 },
    date: '18/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 120,
    employee: { id: 4, matricule: 869 },
    date: '19/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 121,
    employee: { id: 4, matricule: 869 },
    date: '20/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 122,
    employee: { id: 4, matricule: 869 },
    date: '21/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 123,
    employee: { id: 4, matricule: 869 },
    date: '22/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 124,
    employee: { id: 4, matricule: 869 },
    date: '23/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 125,
    employee: { id: 4, matricule: 869 },
    date: '24/01/2023',
    heure_normale: 8,
    heure_de_travail: 8,
    hs_de_nuit: null,
    hs_jours_feries: null,
  },
  {
    id: 126,
    employee: { id: 4, matricule: 869 },
    date: '25/01/2023',
    heure_normale: 8,
    heure_de_travail: 10,
    hs_de_nuit: null,
    hs_jours_feries: 10,
  },
]

const toAdd = data
  .map((item) => {
    if (item.employee.id === 1) {
      return {
        ...item,
        id: item.id + 84,
        employee: {
          id: 4,
          matricule: 869,
        },
      }
    }

    return null
  })
  .filter((item) => item !== null)

const out = data
  .map((item) => {
    if (Array.isArray(item.hs_de_nuit)) {
      return {
        ...item,
        hs_de_nuit: null,
      }
    }
    return null
  })
  .filter((item) => item !== null)

const filePath = path.join(__dirname, 'jsonConverted.json')

// Write the modified data to a file
fs.writeFile(filePath, JSON.stringify([...data, ...out]), (err) => {
  if (err) {
    console.error(err)
  } else {
    console.log('File updated successfully.')
  }
})
