# Utilisez une image de base Apache
FROM httpd:latest

# Copiez le fichier de configuration de virtual host vers le conteneur
COPY ./docker/apache_docker/httpd.conf /usr/local/apache2/conf/httpd.conf
