version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/docker_app/Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: .
      dockerfile: docker/docker_nginx/Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - app
