services:
  app:
    container_name: la-ligne-scandinave-front-end
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/app_docker/Dockerfile
    expose:
      - 3000:3000
    env_file:
      - .env
