services:
  app:
    container_name: la-ligne-scandinave-front-end
    build:
      context: .
      dockerfile: docker/app_docker/Dockerfile
    env_file:
      - .env
    expose:
      - '3000:81'
    ports:
      - '3000:81'